version: '3'

services:
    db:
        container_name: postgres
        image: postgres:12-alpine
        environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: postgres
            POSTGRES_DB: postgres
        ports:
            - "5432:5432"
        volumes:
            - pgstore:/var/lib/postgresql/data
            - ./query/initialize:/docker-entrypoint-initdb.d

volumes:
    pgstore:
